# -*- coding: utf-8 -*-
"""OIBSIP_TASKNO4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fTkw42I24pFpF2QbUWqihO6yCDW_bNo1
"""

import random
def get_weather(location):
    # Simulating weather data with random values
    temperature = random.uniform(-10, 40)
    humidity = random.uniform(0, 100)
    conditions = ["Clear", "Cloudy", "Rainy", "Snowy"]
    weather_condition = random.choice(conditions)
    print(f"\nSimulated Weather condition in {location.capitalize()}:")
    print(f"Temperature: {temperature:.2f}°C")
    print(f"Humidity: {humidity:.2f}%")
    print(f"Conditions: {weather_condition}")
def main():
    location = input("Enter the city name or ZIP code: ")
    get_weather(location)
if __name__ == "__main__":
    main()